In [1]:
import sys
import pandas as pd
import tools
import logging

sys.path.append('../database')  # Add the 'database' directory to the Python path
sys.path.append('../../')   
from db_connections import get_database_connection

Engine(postgresql://postgres:***@localhost:5432/financas)

In [2]:
class Bank_Statement_Pipeline:
    """Pipeline de ingestão de dados
     Attributes
    ----------
    type: str
        Define what type of extraction. Options: csv
    origin_path: str
        address of the extraction data
    load_path: str
        Address of the load table

    Methods
    extract():
        Extracts the information
    tranform()
    load()
    """



    def __init__(self) -> None:
        self.df=None
        self.cliente_id=None
        self.conta_id=None
        self.load_path=None
    def extract(self,origin_path):
        self.df = pd.read_excel(origin_path)
        file_name=tools.get_fileName_from_filePath(origin_path)
        self.cliente_id=tools.get_userId_from_fileName(file_name)
        self.conta_id=tools.get_accountId_from_fileName(file_name)
        

    def transform(self):
        df = self.df.copy()
        # Encontrando primeira linha relevante
        first_line=-1
        #Finding first line
        for index,row in df.iterrows():
            if row.iloc[0]=='data':
                first_line=index
                break
        # Get relevante lines
        df=df.iloc[first_line:]
        # Promote first line to columns
        df.columns=df.iloc[0].to_list()
        df =df.iloc[1:]

        #Limpando linhas desnecessárias
        #Dropando lançamentos futuros
        df.reset_index(drop=True,inplace=True)
        index = df[df['data'] == 'lançamentos futuros'].index.item()
        df=df.iloc[0:index]

        #Dropand linhas de saldo
        df.dropna(subset=['valor (R$)'],inplace=True)
        df.reset_index(drop=True,inplace=True)


        #Dropando colunas Desnecessarias   saldos (R$) e ag./origem 
        df=df.drop(columns=['saldos (R$)','ag./origem'])

        df['tipo_transacao']='conta'
        df['conta_id']=self.conta_id
        df['usuario_id']=self.cliente_id
        
        #Renomeando colunas
        df.rename(columns={'data':'data','lançamento':'ref_fonte','valor (R$)':'valor','tipo_transacao':'tipo_transacao', 'conta_id':'conta_id','usuario_id':'usuario_id'},
                       inplace=True)
        
        self.df=df


    def load(self,load_path='fato.transacao'):
        engine,connection=get_database_connection(existDB=True,engine='sqlAlchemy')
        n=self.df.to_sql(load_path, connection, if_exists='append', index=False)
        connection.commit()
        connection.close()

        tools.load_legado(self.df,'extrato')

In [3]:
origin_path='files\\extratos\\1_1_extrato_202512.xls'
pipeline=Bank_Statement_Pipeline()
log = logging.getLogger(__name__)
log.info('Extraindo Dados')
pipeline.extract(origin_path)
pipeline.df

,Logotipo Itaú,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Atualização:,08/01/2026 às 11:03:43,NaN,NaN,NaN
1,Nome:,ALBERT MAZUZ,NaN,NaN,NaN
2,Agência:,4086,NaN,NaN,NaN
3,Conta:,12304-1,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
84,31/12/2025,SALDO TOTAL DISPONÃVEL DIA,NaN,NaN,6370.68
85,lançamentos futuros,NaN,NaN,NaN,NaN
86,saídas futuras,NaN,NaN,NaN,NaN
87,12/01/2026,DA COMGAS 43015611,NaN,-80.49,NaN
88,15/01/2026,DA CLARO BL/IT 83566075,NaN,-165.24,NaN

In [4]:
log.info('Transformando Dados')
pipeline.transform()
pipeline.df

,data,ref_fonte,valor,tipo_transacao,conta_id,usuario_id
0,01/12/2025,RSCSS-AUTO POSTO -29/11,-140.19,conta,1,1
1,01/12/2025,PIX QRS S.A PARK VA30/11,-25,conta,1,1
2,01/12/2025,REND PAGO APLIC AUT MAIS,0.01,conta,1,1
3,03/12/2025,PIX QRS DROGARIA SA03/12,-69.99,conta,1,1
4,04/12/2025,PIX TRANSF JESSICA04/12,453.75,conta,1,1
5,04/12/2025,PIX TRANSF SONIA B04/12,-250,conta,1,1
6,08/12/2025,PIX QRS MADALENAPET08/12,-218.46,conta,1,1
7,08/12/2025,PAG BOLETO SANDRA REGINA DE ANDRADE,-3771.05,conta,1,1
8,08/12/2025,REND PAGO APLIC AUT MAIS,0.07,conta,1,1
9,08/12/2025,DA COMGAS 43015611,-79.59,conta,1,1
10,09/12/2025,PIX TRANSF SONIA B09/12,-250,conta,1,1
11,09/12/2025,PIX TRANSF ANIMAU 09/12,-398.56,conta,1,1
12,09/12/2025,REND PAGO APLIC AUT MAIS,0.02,conta,1,1
13,15/12/2025,PIX TRANSF ALBERT 13/12,3500,conta,1,1
14,15/12/2025,APLICACAO COFRINHOS,-3500,conta,1,1
15,15/12/2025,PIX TRANSF JESSICA13/12,5000,conta,1,1
16,15/12/2025,RSCSS PEG PESE SUP1412,-159.03,conta,1,1
17,15/12/2025,RSCSS AUTO POSTO L1412,-194.35,conta,1,1
18,15/12/2025,RSCCS PG FRANQ PE1412,-100.3,conta,1,1
19,15/12/2025,PAG BOLETO MAPLE DA VILA ENSINO BILINGU,-3000.04,conta,1,1
20,15/12/2025,PIX TRANSF ALBERT 15/12,3600,conta,1,1
21,15/12/2025,DA CLARO BL/IT 83566075,-164.94,conta,1,1
22,17/12/2025,PIX QRS HORTIFRUTI 17/12,-25.51,conta,1,1
23,17/12/2025,PIX TRANSF Josefa 17/12,-200,conta,1,1
24,17/12/2025,REND PAGO APLIC AUT MAIS,0.02,conta,1,1
25,18/12/2025,PIX TRANSF VIOLETA18/12,-600,conta,1,1
26,18/12/2025,REND PAGO APLIC AUT MAIS,0.06,conta,1,1
27,19/12/2025,PIX TRANSF FISIOKI19/12,-350,conta,1,1
28,19/12/2025,PIX TRANSF SONIA B19/12,-370,conta,1,1
29,19/12/2025,PIX TRANSF ALBERT 19/12,1250,conta,1,1
30,19/12/2025,APLICACAO COFRINHOS,-1250,conta,1,1
31,19/12/2025,PERS BLACK 3600-8022,-4333.91,conta,1,1
32,19/12/2025,REND PAGO APLIC AUT MAIS,0.15,conta,1,1
33,22/12/2025,PIX QRS HORTIFRUTI 20/12,-26.21,conta,1,1
34,22/12/2025,RSCSS SWIFT PINHEI2112,-158.9,conta,1,1
35,22/12/2025,RSCSS HORTIFRUTI P2112,-135.63,conta,1,1
36,22/12/2025,PIX QRS HORTIFRUTI 21/12,-43.99,conta,1,1
37,22/12/2025,PIX TRANSF MARCOS 22/12,-50,conta,1,1
38,22/12/2025,REND PAGO APLIC AUT MAIS,0.01,conta,1,1
39,23/12/2025,RSCSS HORTIFRUTI P2312,-88.1,conta,1,1
40,23/12/2025,RSHOP AUTO POSTO L2312,-171.57,conta,1,1
41,23/12/2025,RSHOP NATURA PAY 02312,-125.72,conta,1,1
42,23/12/2025,RSHOP SWIFT PINHEI2312,-69.8,conta,1,1
43,23/12/2025,PIX TRANSF SONIA B23/12,-250,conta,1,1
44,23/12/2025,RESGATE CDB Cofrinhos,600.01,conta,1,1
45,23/12/2025,PIX QRS QUITANDA FR23/12,-23.06,conta,1,1
46,23/12/2025,PIX QRS TODOMODA23/12,-94.7,conta,1,1
47,23/12/2025,REND PAGO APLIC AUT MAIS,0.01,conta,1,1
48,24/12/2025,DA ELETROPAULO 84896637,-225.06,conta,1,1
49,24/12/2025,REND PAGO APLIC AUT MAIS,0.01,conta,1,1
50,29/12/2025,PIX TRANSF JESSICA29/12,4000,conta,1,1
51,29/12/2025,APLICACAO COFRINHOS,-400,conta,1,1
52,29/12/2025,APLICACAO COFRINHOS,-129,conta,1,1
53,30/12/2025,PIX TRANSF SONIA B30/12,-250,conta,1,1
54,30/12/2025,PIX TRANSF ALBERT 30/12,3200,conta,1,1
55,31/12/2025,PIX QRS RENNER31/12,-565.4,conta,1,1
56,31/12/2025,PIX TRANSF JESSICA31/12,186,conta,1,1
57,31/12/2025,PIX TRANSF VANESSA31/12,-100,conta,1,1
58,31/12/2025,PIX TRANSF RAFAELA31/12,-100,conta,1,1
59,31/12/2025,REND PAGO APLIC AUT MAIS,0.04,conta,1,1

In [5]:
df

NameError: name 'df' is not defined

In [ ]:
df = pipeline.df
# Encontrando primeira linha relevante
first_line=-1
#Finding first line
df
for index,row in df.iterrows():
    if row.iloc[0]=='data':
        first_line=index
        break
# Get relevante lines
df=df.iloc[first_line:]
# Promote first line to columns
df.columns=df.iloc[0].to_list()
df =df.iloc[1:]

#Limpando linhas desnecessárias
#Dropando lançamentos futuros
df.reset_index(drop=True,inplace=True)
df

index = df[df['data'] == 'lançamentos futuros'].index.item()
df=df.iloc[0:index]

#Dropand linhas de saldo
df.dropna(subset=['valor (R$)'],inplace=True)
df.reset_index(drop=True,inplace=True)


#Dropando colunas Desnecessarias   saldos (R$) e ag./origem 
df=df.drop(columns=['saldos (R$)','ag./origem'])

#Renomeando colunas
df.rename(columns={'data':'data','lançamento':'ref_fonte','valor (R$)':'valor','tipo_transacao':'tipo_transacao', 'conta_id':'conta_id','usuario_id':'usuario_id'},
                inplace=True)
df

          data                                ref_fonte    valor
0   01/12/2025                  RSCSS-AUTO POSTO -29/11  -140.19
1   01/12/2025                 PIX QRS S.A PARK VA30/11      -25
2   01/12/2025                 REND PAGO APLIC AUT MAIS     0.01
3   03/12/2025                 PIX QRS DROGARIA SA03/12   -69.99
4   04/12/2025                  PIX TRANSF JESSICA04/12   453.75
5   04/12/2025                  PIX TRANSF SONIA B04/12     -250
6   08/12/2025                 PIX QRS MADALENAPET08/12  -218.46
7   08/12/2025      PAG BOLETO SANDRA REGINA DE ANDRADE -3771.05
8   08/12/2025                 REND PAGO APLIC AUT MAIS     0.07
9   08/12/2025                      DA  COMGAS 43015611   -79.59
10  09/12/2025                  PIX TRANSF SONIA B09/12     -250
11  09/12/2025                  PIX TRANSF ANIMAU 09/12  -398.56
12  09/12/2025                 REND PAGO APLIC AUT MAIS     0.02
13  15/12/2025                  PIX TRANSF ALBERT 13/12     3500
14  15/12/2025                      APLICACAO COFRINHOS    -3500
15  15/12/2025                  PIX TRANSF JESSICA13/12     5000
16  15/12/2025                   RSCSS PEG PESE SUP1412  -159.03
17  15/12/2025                   RSCSS AUTO POSTO L1412  -194.35
18  15/12/2025                   RSCCS PG  FRANQ PE1412   -100.3
19  15/12/2025  PAG BOLETO MAPLE DA VILA ENSINO BILINGU -3000.04
20  15/12/2025                  PIX TRANSF ALBERT 15/12     3600
21  15/12/2025                 DA  CLARO BL/IT 83566075  -164.94
22  17/12/2025                 PIX QRS HORTIFRUTI 17/12   -25.51
23  17/12/2025                  PIX TRANSF Josefa 17/12     -200
24  17/12/2025                 REND PAGO APLIC AUT MAIS     0.02
25  18/12/2025                  PIX TRANSF VIOLETA18/12     -600
26  18/12/2025                 REND PAGO APLIC AUT MAIS     0.06
27  19/12/2025                  PIX TRANSF FISIOKI19/12     -350
28  19/12/2025                  PIX TRANSF SONIA B19/12     -370
29  19/12/2025                  PIX TRANSF ALBERT 19/12     1250
30  19/12/2025                      APLICACAO COFRINHOS    -1250
31  19/12/2025                    PERS BLACK  3600-8022 -4333.91
32  19/12/2025                 REND PAGO APLIC AUT MAIS     0.15
33  22/12/2025                 PIX QRS HORTIFRUTI 20/12   -26.21
34  22/12/2025                   RSCSS SWIFT PINHEI2112   -158.9
35  22/12/2025                   RSCSS HORTIFRUTI P2112  -135.63
36  22/12/2025                 PIX QRS HORTIFRUTI 21/12   -43.99
37  22/12/2025                  PIX TRANSF MARCOS 22/12      -50
38  22/12/2025                 REND PAGO APLIC AUT MAIS     0.01
39  23/12/2025                   RSCSS HORTIFRUTI P2312    -88.1
40  23/12/2025                   RSHOP AUTO POSTO L2312  -171.57
41  23/12/2025                   RSHOP NATURA PAY 02312  -125.72
42  23/12/2025                   RSHOP SWIFT PINHEI2312    -69.8
43  23/12/2025                  PIX TRANSF SONIA B23/12     -250
44  23/12/2025                    RESGATE CDB Cofrinhos   600.01
45  23/12/2025                 PIX QRS QUITANDA FR23/12   -23.06
46  23/12/2025                    PIX QRS TODOMODA23/12    -94.7
47  23/12/2025                 REND PAGO APLIC AUT MAIS     0.01
48  24/12/2025                 DA  ELETROPAULO 84896637  -225.06
49  24/12/2025                 REND PAGO APLIC AUT MAIS     0.01
50  29/12/2025                  PIX TRANSF JESSICA29/12     4000
51  29/12/2025                      APLICACAO COFRINHOS     -400
52  29/12/2025                      APLICACAO COFRINHOS     -129
53  30/12/2025                  PIX TRANSF SONIA B30/12     -250
54  30/12/2025                  PIX TRANSF ALBERT 30/12     3200
55  31/12/2025                      PIX QRS RENNER31/12   -565.4
56  31/12/2025                  PIX TRANSF JESSICA31/12      186
57  31/12/2025                  PIX TRANSF VANESSA31/12     -100
58  31/12/2025                  PIX TRANSF RAFAELA31/12     -100
59  31/12/2025                 REND PAGO APLIC AUT MAIS     0.04

In [ ]:
log.info('Carregando Dados')
pipeline.load('financas.fato.transacao')

KeyError: 'ref_original'